### ISSUE TITLE
what gateway capability 1 << 12 might do

### ISSUE THREAD

**Issue by kissingboys** [ouwou/discord-undocumented#3]
hello I was trying to figure out what this capability might do https://github.com/ouwou/discord-undocumented/blob/2d0cad695b4e8b666daff851752df7a7f625eac0/docs/capabilities.md?plain=1#L23
from what I found on discord.py-self it's used for "auto call connect" i hope this can be useful

**Comment by ouwou** [comment]
thank you boykisser i had to figure this out myself a while ago but forgot to update this page. i will do it today i think
